[project]
name = "linkedin-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.68.2",
    "openai-agents>=0.0.15",
    "playwright>=1.51.0",
    "playwright-stealth>=2.0.0",
    "jupyter",
    "ipykernel",
    "nest-asyncio>=1.6.0",
    "uvicorn>=0.40.0",
    "fastapi>=0.128.0",
    "dateparser>=1.2.2",
    "dotenv>=0.9.9",
    "python-dotenv>=1.2.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    
]


